# 8장 예외처리

# 프로그램 오류

- 컴파일 에러 ( Complie-time Error ) : 컴파일 할 때 발생하는 에러
    
    ⇒ javac 로 해당 클래스 컴파일할 때 나타나는 에러
    
    - 자바 컴파일러
        1. 구문체크
        2. 번역
        3. 최적화
        4. 생략된 코드들 추가
- 런타임 에러 ( Runtime Error ) : 실행 중 발생하는 에러
    - 실행 하다가 에러 발생 시 프로세스 종료
- 논리적 에러 ( Logical Error ) : 작성의도와 다르게 동작
    - 프로세스 종료 X

# Java 런타임 에러

- 자바에서는 런타임 에러 종류를 에러와 예외로 구분
- 에러 : 프로그램 코드에 의해 수습될 수 없는 심각한 오류
    - ex) OutOfMemory
- 예외 : 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류

⇒ 에러는 어쩔 수 없지만 예외는 처리하자

# 예외처리의 정의와 목적

- 정의 : 프로그램 실행 시 발생할 수 있는 예외(다소 미약한 오류)의 발생에 대비한 코드를 작성하는 것
- 목적 : 프로그램의 비정상 종료를 막고, 정상적인 실행상태 유지
    - 비정상 종료시 데이터가 사라진다.

- 예외 클래스 계층 구조
    - Object : 최고 조상
        - Throwable : 오류의 조상
            - Error : 심각한 오류 (런타임 에러)
            - Exception : 다소 미약한 오류 (런타임 에러)
                - IOException : 입출력 에러
                - ClassNotFountException : 클래스를 못찾는 에러
                - ….
                - RuntimeException
                    - ArithmeticException → 산술 계산 예외 ex : 5/0
                    - ClassCastException → 형변환 예외
                    - NullPointerException → 널포인터 예외
                    - ….
                    - IndexOutOfBoundsException → 배열 범위 벗어남

# Exception 과 RuntimeException

- Exception 클래스들 (Exception과 그 자식들 , RuntimeException 제외) : 사용자의 실수와 같은 외적인 요인에 의해 발생하는 예외
- RuntimeException 클래스들 : 프로그래머의 실수로 발생하는 예외

# 예외 처리하기 try - catch

- 예외 처리 시 사용하는 문법
- try 블럭에서 에외 발생 시 catch 블럭 찾아감 → catch 블럭 처리 후 밖으로 나감
- catch가 없다면 애플리케이션 비정상 종료
- Exception 선언은 캐치 블록의 마지막으로 가야 한다
    - Exception은 모든 예외의 조상 → 모든 예외 처리가 걸린다.

- printStackTrace() 와 getMessage()
    - printStackTrace() : 에외 발생시 호출스택에 있었던 메서드 정보와 예외 메시지 출력
    - getMessage() : 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.

# 예외 발생시 일어나는 일

1. 예외 발생 → 예외 객체 생성
    
    ⇒ 예외 객체 내 메서드에 printStackTrace() , getMessage()가 있다. ( 그외 다른 메서드들도 존재)
    
2. 예외 객체와 catch 매개변수 맞는 곳에서 처리 → 해당 캐치 블럭 내에서만 예외객체 참조변수 사용 

# 멀티 catch 블럭

- 내용이 같은 catch 블럭을 하나로 합친것 (JDK 1.7부터)
    
    } catch (ExceptionA | Exception B e) {
    
    }
    
- 부모 자식 관계 X why? 부모만 써도 된다.
- 한 예외클래스에만 있는 메서드 호출X
    - 굳이 사용하려면 instanceof 연산자 이용 → 이러면 멀티 catch 블럭 사용이유가 사라짐

# 예외 발생시키기

1. 연산자 new 를 이용해서 발생시키려는 예외 클래스의 객체를 만든 다음
2. 키워드 throw를 이용해서 예와 발생 

# checked 예외 , unchecked 예외

- checked 예외 : 컴파일러가 예외처리 여부를 체크(예외 처리 필수) ⇒ Exception 클래스들
- unchecked 예외 : 컴파일러가 예외처리 여부 체크 안함(예외처리 선택) ⇒ RuntimeException 클래스들

# 메서드에 예외 선언

- 예외 처리 방법
    1. try-catch 문 (직접처리)
    2. 예외 선언하기 ( 예외 떠넘기기 , 알리기 ) → 호출한 쪽으로 
    3. 은폐 (덮기) → try-catch 문에 아무것도 안쓰기 → 대량의 빅데이터를 작업 시 고려 ( 대부분 사용 X )
- 예외 선언 방법
    - 메서드 이름() throws 예외선언
    - throws에 체크드 예외만 적는 것이 정석
- 끝까지 에외처리 없이 떠넘기기만 한다면 비정상 종료 후 JVM기본 예외처리기가 출력
- 이 예외는 작업을 처리하는 메서드가 처리할지 작업을 시킨 메서드가 처리 할지에 따라 try-catch문과 예외선언하는 곳이 정해짐

# finally 블럭

- 예외 발생 여부와 관계 없이 수행되어야 하는 코드
- try 블럭 안에 return 문이 있어서 try블럭을 벗어나갈 때도 finally블럭이 작동
- catch와 try에 중복 코드가 있다면 finally 블럭을 사용하자\

# 사용자 정의 예외 만들기

- 직접 예외 클래스 정의
- 조상은 Exception과 RuntimeException 중에서 선택 (필수 처리할건지 , 선택처리할건지 )
    - 대부분 RuntimeException 선택
- 예외 메시지를 받는 생성자 기본
    
    super(msg);
    

# 예외 되던지기 (Exception re-throwing)

- 예외 처리 후 예외 다시 발생
- 호출한 메서드와 호출된 메서드 양쪽 모두 예외처리 (2번 처리된다)
- 언제 사용할까?
    - 작업중인 메서드에서 일부처리, 호출한 메서드에서 나머지 처리가 필요해보일 때 사용

# 연결된 예외(chained exception)

- 한 예외가 다른 예외를 발생 시킬 수 있다.
- 예외 A가 예외 B를 발생시키면, A는 B의 원인 에러(cause exception)
- Throwable 클래스에 cause 멤버변수있다.
- 메서드
    - Throwable initCause(Throwable cause) → 지정한 예외를 원인 예외로 등록
    - Throwable getCause(); → 원인 예외 조회
- 이유
    - 여러 예외를 하나로 묶어서 다루기 위해 , 세부정보 사용 가능
        - catch 블록이 많아질 때 사용
    - checked 예외를 unchecked 예외로 변경하려 할 때
        - 상속 계층도를 변경하기 어려울 때